package metrics

import (
	"sync"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// MetricData holds collected metric information
type MetricData struct {
	Model            string        `json:"model"`
	Endpoint         string        `json:"endpoint"`
	Category         string        `json:"category"`
	InputTokens      int           `json:"input_tokens"`
	OutputTokens     int           `json:"output_tokens"`
	Duration         time.Duration `json:"duration"`
	TimeToFirstToken int           `json:"time_to_first_token"`
}

// Global metrics registry
var (
	// Request counters by category
	requestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ollama_requests_total",
			Help: "Total number of Ollama API requests",
		},
		[]string{"model", "endpoint", "category", "status"},
	)

	// Request duration histogram
	requestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "ollama_request_duration_seconds",
			Help:    "Request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"model"},
	)

	// Tokens generated counter
	tokensGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ollama_tokens_generated",
			Help: "Total tokens generated by Ollama",
		},
		[]string{"model", "token_type"}, // token_type: input/output
	)

	// Active requests gauge
	activeRequests = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_active_requests",
			Help: "Current number of active requests",
		},
		[]string{"model"},
	)

	// Token generation rate
	tokensPerSecond = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_tokens_per_second",
			Help: "Estimated tokens per second",
		},
		[]string{"model"},
	)

	// Backend health metric
	backendHealth = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_backend_health",
			Help: "Ollama backend health (1=healthy, 0=unhealthy)",
		},
		[]string{"backend"},
	)
)

var (
	// Model statistics tracking
	modelStatsMu sync.RWMutex
	modelStats   = make(map[string]*modelStatistics)

	// Token generation time tracking
	lastTokenTimeMu sync.RWMutex
	lastTokenTime   = make(map[string]time.Time)
)

type modelStatistics struct {
	TotalInputTokens     int
	TotalOutputTokens    int
	TotalRequestCount    int
	TotalRequestDuration time.Duration
	FirstSeen            time.Time
}

// RecordActiveRequests updates the active requests gauge
func RecordActiveRequests(model string, delta int) {
	activeRequests.WithLabelValues(model).Add(float64(delta))
}

// RecordCompletedRequest records metrics for a completed request
func RecordCompletedRequest(data MetricData) {
	// Record request counter
	requestsTotal.WithLabelValues(data.Model, data.Endpoint, data.Category, "success").Inc()

	// Record request duration
	requestDuration.WithLabelValues(data.Model).Observe(data.Duration.Seconds())

	// Track tokens
	if data.InputTokens > 0 {
		tokensGenerated.WithLabelValues(data.Model, "input").Add(float64(data.InputTokens))
	}
	if data.OutputTokens > 0 {
		tokensGenerated.WithLabelValues(data.Model, "output").Add(float64(data.OutputTokens))
	}

	// Update model statistics
	modelStatsMu.Lock()
	if stats, ok := modelStats[data.Model]; ok {
		stats.TotalInputTokens += data.InputTokens
		stats.TotalOutputTokens += data.OutputTokens
		stats.TotalRequestCount++
		stats.TotalRequestDuration += data.Duration
	} else {
		modelStats[data.Model] = &modelStatistics{
			TotalInputTokens:     data.InputTokens,
			TotalOutputTokens:    data.OutputTokens,
			TotalRequestCount:    1,
			TotalRequestDuration: data.Duration,
			FirstSeen:            time.Now(),
		}
	}
	modelStatsMu.Unlock()

	// Track token generation speed
	if data.OutputTokens > 0 && data.Duration > 0 {
		tokensPerSecond.WithLabelValues(data.Model).Set(float64(data.OutputTokens) / data.Duration.Seconds())
	}
	if data.TimeToFirstToken > 0 {
		// Log time to first token information could be added here
		_ = data.TimeToFirstToken
	}
}

// RecordBackendError marks backend as unhealthy
func RecordBackendError(backend string) {
	backendHealth.WithLabelValues(backend).Set(0)
}

// RecordBackendHealth marks backend as healthy
func RecordBackendHealth(backend string) {
	backendHealth.WithLabelValues(backend).Set(1)
}

// GetModelStats retrieves statistics for a specific model
func GetModelStats(model string) (*modelStatistics, bool) {
	modelStatsMu.RLock()
	defer modelStatsMu.RUnlock()
	stats, ok := modelStats[model]
	return stats, ok
}

// GetAllModelStats returns all tracked model statistics
func GetAllModelStats() map[string]*modelStatistics {
	modelStatsMu.RLock()
	defer modelStatsMu.RUnlock()
	// Return a copy to avoid race conditions
	result := make(map[string]*modelStatistics)
	for k, v := range modelStats {
		result[k] = v
	}
	return result
}

// Reset resets all metrics (useful for testing)
func Reset() {
	requestsTotal.Reset()
	requestDuration.Reset()
	tokensGenerated.Reset()
	activeRequests.Reset()
	tokensPerSecond.Reset()
	backendHealth.Reset()

	modelStatsMu.Lock()
	modelStats = make(map[string]*modelStatistics)
	modelStatsMu.Unlock()

	lastTokenTimeMu.Lock()
	lastTokenTime = make(map[string]time.Time)
	lastTokenTimeMu.Unlock()
}
